### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by codyja** [spinnaker-plugin-examples/nomadPlugin#355]
Hi,
I'm interested in trying out Spinnaker with Nomad but am having some troubles getting started. I have a basic hal and spinnaker instance deployed, but I can't figure out how to properly get the Nomad plugin deployed and usable. If someone could point me in the right direction, I would take a crack at adding more info to the Readme as well. Thanks for any info!

```
# Adding the example repository which includes the Armory.NomadPlugin
hal plugins repository add spinnaker-plugin-examples \
    --url=https://raw.githubusercontent.com/spinnaker-plugin-examples/examplePluginRepository/master/plugins.json

# I believe this installs the plugin
hal plugins add nomad --version=0.0.1 --enabled=true --extensions=Armory.NomadPlugin
```

I can't figure out the proper place to load the example nomad configuration. I've tried the following and a few other variations:

```
bash-5.0$ cat ~/.hal/default/service-settings/clouddriver.yml
spinnaker:
  extensibility:
    plugins:
      Armory.NomadPlugin:
        enabled: true

nomad:
  accounts:
    - name: account1
      environment: dev
      address: http://host.docker.internal:4646
```

Finally I do a `hal deploy apply` but don't see any indication that anything is actually working or not.
